webkaproject/admin_panel/urls.py
from django.urls import path
from . import views


app_name = "admin_panel"

urlpatterns = [
    path('', views.main_admin_panel, name='admin_main'),
    path('tables/<int:pk>/', views.admin_current_table, name='admin_current_table'),

    path('accept_data', views.accept_change_data, name='accept_data'),
    path('add_modal_form', views.add_modal_form, name='add_modal_form'),

    path('accept_add_data', views.accept_add_data, name='accept_add_data'),
    path('delete_object', views.delete_object, name='delete_object'),

    path('moderate/products', views.ModerateProductList.as_view(), name='moderate_product'),
    path('moderate/products/accept/<int:pk>', views.accept_moderate_product, name='accept_moderate_product'),
    path('moderate/products/cancel/<int:pk>', views.cancel_moderate_product, name='cancel_moderate_product'),

    path('moderate/users', views.ModerateUserList.as_view(), name='moderate_user'),
    path('moderate/users/accept/<int:pk>', views.accept_moderate_user, name='accept_moderate_user'),
    path('moderate/users/cancel/<int:pk>', views.cancel_moderate_user, name='cancel_moderate_user'),

]

webkaproject/auction/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from auction.views import AuctionListView, AuctionDetailView

app_name = 'auction'

urlpatterns = [
    path('', AuctionListView.as_view(), name = 'auction_main'),
    path('lot/<int:pk>', AuctionDetailView.as_view(), name = 'auction_detail')
]

webkaproject/marketplace1/urls.py
from django.urls import path
from . import views


app_name = "marketplace1"

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('product/<int:pk>/', views.product_detail, name='product_detail'),
    path('delete/<int:product_id>/', views.delete_product, name='delete_product'),
    path('product/new/', views.NewProductView.as_view(), name='product_new'),
    path('product/<int:pk>/edit', views.product_edit, name='product_edit'),
    path('personal/<int:pk>', views.Personal.as_view(), name='personal_page'),
    path('refill', views.BalanceRefill.as_view(), name='refill_page'),
    path('search', views.SearchResultsView.as_view(), name='search_results'),
    path('favorite', views.FavoriteProductsList.as_view(), name='favorite_products'),
    path('product/<int:pk>/favorite_add', views.add_favorite_product, name='add_favorite_product'),
    path('product/<int:pk>/favorite_delete', views.delete_favorite_product, name='delete_favorite_product'),
    path('product/<int:pk>/favorite_list_delete', views.delete_from_favorit_list, name='delete_from_favorit_list'),
    path('personal/<int:pk>/edit', views.personal_edit, name='personal_edit'),

]

webkaproject/webkaproject/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns = [
        path('admin/', admin.site.urls),
        path('', include('marketplace1.urls')),
        path('auth/', include('authorization.urls')),
        path('auc/', include('auction.urls')),
        path('dialogs/', include('messenger.urls')),
        path('admin1/', include('admin_panel.urls')),

    ]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#
# else:
#     urlpatterns = [
#         path('admin/', admin.site.urls),
#         path('', include('marketplace1.urls')),
#         path('auth/', include('authorization.urls')),
#         path('auc/', include('auction.urls')),
#         path('dialogs/', include('messenger.urls')),
#     ]

webkaproject/admin_panel/models.py
from django.db import models

# Create your models here.

webkaproject/admin_panel/forms.py
from django import forms
from bootstrap_modal_forms.generic import BSModalCreateView
import models

webkaproject/admin_panel/views.py
from django.shortcuts import render
from django.apps import apps
from django.shortcuts import get_object_or_404
from django.forms import modelform_factory, inlineformset_factory
from django.forms.models import fields_for_model
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView
from django.shortcuts import redirect
from account.models import Account
from marketplace1.models import Product
from django.contrib import messages



class Counter:
    count = 0

    def increment(self):
        self.count += 1
        return ''

    def decrement(self):
        self.count -= 1
        return ''

    def double(self):
        self.count *= 2
        return ''


from django.forms import ModelForm
from django.forms.models import model_to_dict
from django.template.loader import render_to_string
from django.http import JsonResponse


def get_model(num):
    mods = apps.get_models()  # все модели
    model_names = []
    models = []
    for mod in mods:
        if mod._meta.verbose_name[0].isupper():
            model_names.append(mod._meta.verbose_name)
            models.append(mod)
    return models[num]


def get_values_of_objects(objects, object_fields):
    values = []
    for obj in objects:
        temp = []
        for field in object_fields:
            temp.append(getattr(obj, field.name))
        values.append(temp)
    return values


def main_admin_panel(request):
    mods = apps.get_models()  # все модели
    model_names = []
    for mod in mods:
        if mod._meta.verbose_name[0].isupper():
            model_names.append(mod._meta.verbose_name)

    counter = Counter()

    return render(request, 'admin_panel/main_admin_list_page.html', {'table_names': model_names, 'counter': counter})


@csrf_exempt
def admin_current_table(request, pk):
    context = {}
    selected_model = get_model(pk)  # выбранная пользователем модель(тип данных)

    selected_model_fields = selected_model._meta.fields  # поля принадлежащие модели

    selected_model_objects = selected_model.objects.order_by(
        'id')  # все объекты выбранного типа данных отсортированные по id

    values_of_fields = get_values_of_objects(selected_model_objects, selected_model_fields)  # значения объекта

    field_names = []  # имена полей(столбцов таблицы)

    if request.method == "POST":
        obj_id = request.POST.get('object_id')

        for field in selected_model_fields:  # получаем список имён полей для генерации формы
            if field.editable:
                field_names.append(field.name)

        temp_form = modelform_factory(selected_model,
                                      fields=field_names)  # Форма для выбранного объекта, может используется для создания новой формы, поэтому temp
        obj = get_object_or_404(selected_model, pk=obj_id)  # получаем объект выбранной модели
        form = temp_form(instance=obj)
        modal_context = {
            'form': form,
            'user': request.user,
            'obj': obj,
            'selected_model_name': selected_model._meta.verbose_name,
            'selected_model_objects': selected_model_objects,
            'fields': selected_model_fields,
            'values_of_fields': values_of_fields,
            'tabnum': int(pk),
        }
        result = render_to_string('includes/modal_change_object.html', modal_context)
        return JsonResponse({'result': result})

    context['selected_model_name'] = selected_model._meta.verbose_name
    context['selected_model_objects'] = selected_model_objects
    context['fields'] = selected_model_fields
    context['values_of_fields'] = values_of_fields
    context['tabnum'] = int(pk)

    return render(request, 'admin_panel/admin_table.html', context, )


@csrf_exempt
def accept_change_data(request):
    if request.method == 'POST':
        context = {}
        selected_model = get_model(int(request.POST.get('tab_id')))  # выбранная пользователем модель(тип данных)
        obj = get_object_or_404(selected_model,
                                pk=int(request.POST.get('object_id')))  # получаем объект выбранной модели
        selected_model_objects = selected_model.objects.order_by(
            'id')  # все объекты выбранного типа данных отсортированные по id

        selected_model_fields = selected_model._meta.fields  # поля принадлежащие модели
        field_names = []  # имена полей(столбцов таблицы)
        for field in selected_model_fields:  # получаем список имён полей для генерации формы
            if field.editable:
                field_names.append(field.name)

        temp_form = modelform_factory(selected_model,
                                      fields=field_names)

        form = temp_form(request.POST, instance=obj)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.save()
        values_of_fields = get_values_of_objects(selected_model_objects, selected_model_fields)  # значения объекта
        context['selected_model_name'] = selected_model._meta.verbose_name
        context['selected_model_objects'] = selected_model_objects
        context['fields'] = selected_model_fields
        context['values_of_fields'] = values_of_fields
        context['tabnum'] = int(request.POST.get('tab_id'))
        context['script_path'] = "/static/js/admin_actions.js"
        result = render_to_string('includes/table_objects.html', context)
        return JsonResponse({'result': result})

        # return render(request, 'admin_panel/admin_table.html', context)


@csrf_exempt
def add_modal_form(request):
    if request.method == "POST":
        context = {}
        selected_model = get_model(int(request.POST.get('tab_id')))  # выбранная пользователем модель(тип данных)
        selected_model_fields = selected_model._meta.fields  # поля принадлежащие модели
        field_names = []  # имена полей(столбцов таблицы)
        for field in selected_model_fields:  # получаем список имён полей для генерации формы
            if field.editable:
                field_names.append(field.name)
        add_form = modelform_factory(selected_model,
                                     fields=field_names)  # Форма для выбранного объекта, может используется для создания новой формы, поэтому temp

        context["add_form"] = add_form
        context['selected_model_name'] = selected_model._meta.verbose_name
        context['tabnum'] = int(request.POST.get('tab_id'))
        result = render_to_string('includes/modal_add_object.html', context)
        return JsonResponse({'result': result})


@csrf_exempt
def accept_add_data(request):
    if request.method == "POST":
        context = {}
        selected_model = get_model(int(request.POST.get('tab_id')))  # выбранная пользователем модель(тип данных)

        selected_model_objects = selected_model.objects.order_by(
            'id')  # все объекты выбранного типа данных отсортированные по id
        selected_model_fields = selected_model._meta.fields  # поля принадлежащие модели
        field_names = []  # имена полей(столбцов таблицы)
        for field in selected_model_fields:  # получаем список имён полей для генерации формы
            if field.editable:
                field_names.append(field.name)

        temp_form = modelform_factory(selected_model, fields=field_names)
        form = temp_form(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            print('форма валидная')
            if selected_model == Account:
                obj.set_password(form.cleaned_data['password'])

            obj.save()
        else:
            context_modal_add = {}
            context_modal_add['add_form'] = form
            context_modal_add['tabnum'] = int(request.POST.get('tab_id'))
            print(form.errors)
            result = render_to_string('includes/modal_add_object.html', context_modal_add)
            return JsonResponse({'errors': form.errors, 'result': result})

        values_of_fields = get_values_of_objects(selected_model_objects, selected_model_fields)  # значения объекта

        context['selected_model_name'] = selected_model._meta.verbose_name
        context['selected_model_objects'] = selected_model_objects
        context['fields'] = selected_model_fields
        context['values_of_fields'] = values_of_fields
        context['tabnum'] = int(request.POST.get('tab_id'))
        context['script_path'] = "/static/js/admin_actions.js"
        result = render_to_string('includes/table_objects.html', context)
        return JsonResponse({'result': result})


@csrf_exempt
def delete_object(request):
    if request.method == "POST":
        context = {}
        selected_model = get_model(int(request.POST.get('tab_id')))  # выбранная пользователем модель(тип данных)
        selected_model_objects = selected_model.objects.order_by(
            'id')  # все объекты выбранного типа данных отсортированные по id
        selected_model_fields = selected_model._meta.fields  # поля принадлежащие модели
        field_names = []  # имена полей(столбцов таблицы)
        for field in selected_model_fields:  # получаем список имён полей для генерации формы
            if field.editable:
                field_names.append(field.name)

        obj = get_object_or_404(selected_model,
                                pk=int(request.POST.get('object_id')))  # получаем объект выбранной модели
        obj.delete()
        values_of_fields = get_values_of_objects(selected_model_objects, selected_model_fields)  # значения объекта

        context['selected_model_name'] = selected_model._meta.verbose_name
        context['selected_model_objects'] = selected_model_objects
        context['fields'] = selected_model_fields
        context['values_of_fields'] = values_of_fields
        context['tabnum'] = int(request.POST.get('tab_id'))
        context['script_path'] = "/static/js/admin_actions.js"
        result = render_to_string('includes/table_objects.html', context)

webkaproject/admin_panel/templates/includes/inc_product_item.html
{% load static %}
<div class="blog-card">
    <div class="detail_img pt-0">
        <img src={{ product.image.url }}>
    </div>
    <div class="description">
        <h1>{{ product.title|linebreaksbr }}</h1>
        <h2>Автор:{{ product.author|linebreaksbr }}</h2>
        <h3>Описание:{{ product.description }}</h3>
        <p class="read-more">
            <a href="{% url 'marketplace1:product_detail' pk=product.pk %}">Подробнее</a>
        </p>
    </div>
</div>

webkaproject/admin_panel/templates/includes/inc_user_item.html
{% load static %}
<div class="blog-card">
    <div class="detail_img pt-0">
        <img src={{ acc.avatar.url }}>
    </div>
    <div class="description">
        <h1>Ник:{{ acc.username|linebreaksbr }}</h1>
        <h2>Имя-Фамилия: {{ acc.first_name|linebreaksbr }}-{{ acc.last_name|linebreaksbr }}</h2>
        <h3>Город:{{ acc.country }}</h3>
        <p class="read-more">
            <a href="{% url 'marketplace1:personal_page' pk=acc.pk %}">Подробнее</a>
        </p>
    </div>
</div>

webkaproject/admin_panel/templates/includes/modal_add_object.html
<div class="modal fade" id="addModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Добавить {{ selected_model_name }}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form method="post" id="add_form" enctype="multipart/form-data" class="modal-body">
                {% if messages %}
                {% for message in messages %}
                alert('{{message}}')
                {% endfor %}
                {% endif %}
                <input type="hidden" name="tab_id" value="{{ tabnum }}">
                {{ add_form.as_p }}
            </form>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button id="acceptAddButton" type="button" data-url="{% url 'admin_panel:accept_add_data' %}"
                        name="accept_add_data" class="btn btn-primary">Принять
                </button>

            </div>
        </div>
    </div>
</div>

webkaproject/admin_panel/templates/includes/modal_change_object.html
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Добавить {{ selected_model_name }}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form id="edit_form" enctype='multipart/form-data' class="modal-body">
                <input type="hidden" name="object_id" value="{{ obj.id }}">
                <input type="hidden" name="tab_id" value="{{ tabnum }}">

                {% csrf_token %}
                {{ form.as_p }}
            </form>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button id="acceptButton" type="button" data-url="{% url 'admin_panel:accept_data' %}"
                        name="accept_data" class="btn btn-primary">Принять
                </button>

            </div>
        </div>
    </div>
</div>

webkaproject/admin_panel/templates/includes/table_objects.html
<div class="table_block">
    <table class="table table-bordered table-hover table-dark">
        <thead>
        <tr>
            <th class="functions-table" scope="col">
                Действия
            </th>
            {% for field in fields %}
            <th scope="col">{{ field.name }}</th>
            {% endfor %}
        </tr>
        </thead>
        <tbody>

        {% for obj in values_of_fields %}
        <tr>
            <td class="functions-table">
                <form method="POST" class="d-flex mt-2">
                    {% csrf_token %}
                    <input type="hidden" name="object_id" value="{{ obj.0 }}">
                    <input type="hidden" name="tab_id" value="{{ tabnum }}">
                    <button id="show_change_modal" type="button" data-url="{% url 'admin_panel:admin_current_table' pk=tabnum %}"
                            name="send_object_data" class="btn btn-primary">Редактировать
                    </button>
                    <button id="deleteButton" type="button" data-url="{% url 'admin_panel:delete_object'%}"
                            name="deleteButton" class="btn btn-danger">Удалить
                    </button>
                </form>

            </td>

            {% for value in obj %}
            <td>{{ value }}</td>
            {% endfor %}
        </tr>
        {% endfor %}

        </tbody>
    </table>
</div>