webkaproject/auction/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from auction.views import AuctionListView, AuctionDetailView

app_name = 'auction'

urlpatterns = [
    path('', AuctionListView.as_view(), name = 'auction_main'),
    path('lot/<int:pk>', AuctionDetailView.as_view(), name = 'auction_detail')
]

webkaproject/marketplace1/urls.py
from django.urls import path
from . import views


app_name = "marketplace1"

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('product/<int:pk>/', views.product_detail, name='product_detail'),
    path('delete/<int:product_id>/', views.delete_product, name='delete_product'),
    path('product/new/', views.NewProductView.as_view(), name='product_new'),
    path('product/<int:pk>/edit', views.product_edit, name='product_edit'),
    path('personal/<int:pk>', views.Personal.as_view(), name='personal_page'),
    path('refill', views.BalanceRefill.as_view(), name='refill_page'),
    path('search', views.SearchResultsView.as_view(), name='search_results'),
    path('favorite', views.FavoriteProductsList.as_view(), name='favorite_products'),
    path('product/<int:pk>/favorite_add', views.add_favorite_product, name='add_favorite_product'),
    path('product/<int:pk>/favorite_delete', views.delete_favorite_product, name='delete_favorite_product'),
    path('product/<int:pk>/favorite_list_delete', views.delete_from_favorit_list, name='delete_from_favorit_list'),
    path('personal/<int:pk>/edit', views.personal_edit, name='personal_edit'),

]

webkaproject/messenger/urls.py
from django.urls import path
from . import views


app_name = "messenger"

urlpatterns = [
    path('', views.Dialog_list.as_view(), name='dialog_list'),
    path('<chat_id>/', views.MessagesView.as_view(), name='messages'),
    path('create/<friend_id>/<product_id>', views.create_dialog, name='create_dialog'),
    path('delete/<chat_id>/', views.delete_dialog, name='delete_chat'),

    path('get_messages/<chat_id>/', views.get_messages, name='get_messages'),
    path('get/new_mes_count/', views.get_new_mes_count, name='get_new_mes_count'),
    path('get/update_dialogs/', views.update_chats_list, name='update_dialogs'),
]

webkaproject/webkaproject/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns = [
        path('admin/', admin.site.urls),
        path('', include('marketplace1.urls')),
        path('auth/', include('authorization.urls')),
        path('auc/', include('auction.urls')),
        path('dialogs/', include('messenger.urls')),
        path('admin1/', include('admin_panel.urls')),

    ]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#
# else:
#     urlpatterns = [
#         path('admin/', admin.site.urls),
#         path('', include('marketplace1.urls')),
#         path('auth/', include('authorization.urls')),
#         path('auc/', include('auction.urls')),
#         path('dialogs/', include('messenger.urls')),
#     ]

webkaproject/messenger/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone
from account.models import Account
from marketplace1.models import Product
class ChatManager(models.Manager):
    def unreaded(self, user=None):
        qs = self.get_queryset().exclude(last_message__isnull=True).filter(last_message__is_read=False)
        return qs.exclude(last_message__author=user) if user else qs


class Chat(models.Model):
    product = models.ForeignKey(Product, verbose_name="Товар", on_delete=models.CASCADE)
    members = models.ManyToManyField(Account, verbose_name="Участник", blank=False)
    title = models.CharField(max_length=50, blank=False, verbose_name='Название')
    last_message = models.ForeignKey('Message', related_name='last_message', null=True, blank=True,
                                     on_delete=models.SET_NULL)

    objects = ChatManager()

    class Meta:
        verbose_name = 'Чаты'
        verbose_name_plural = 'Чаты'
        ordering = ('-last_message',)

    def __str__(self):
        return str(self.members.all())


class Message(models.Model):
    chat = models.ForeignKey(Chat, verbose_name="Чат", on_delete=models.CASCADE)
    author = models.ForeignKey(Account, verbose_name="Пользователь", on_delete=models.DO_NOTHING)
    message = models.TextField("Сообщение")
    pub_date = models.DateTimeField('Дата сообщения', default=timezone.now)
    is_read = models.BooleanField('Прочитано', default=False)

    class Meta:
        ordering = ('pub_date',)
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'

    def __str__(self):
        return self.message


@receiver(post_save, sender=Message)
def post_save_comment(sender, instance, created, **kwargs):
    if created:
        instance.chat.last_message = instance
        instance.chat.save(update_fields=['last_message'])

webkaproject/messenger/forms.py
from django.forms import ModelForm

from messenger.models import Message


class MessageForm(ModelForm):
    class Meta:
        model = Message
        fields = ['message']
        labels = {'message': ""}

webkaproject/messenger/views.py
from django.db.models import Q
from django.http import JsonResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.template.loader import render_to_string
from django.urls import reverse
from account.models import Account
from messenger.forms import MessageForm
from messenger.models import Chat
from django.views import View
from django.views.generic import TemplateView
from django.contrib.auth import get_user_model

User = get_user_model()

class Dialog_list(TemplateView):
    template_name = 'messenger/dialogs.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        data = super(Dialog_list, self).get_context_data()
        data['chats'] = Chat.objects.filter(members__in=[self.request.user.id])

        return data



class MessagesView(View):
    def get(self, request, chat_id):
        try:
            chat = Chat.objects.get(id=chat_id)
            if request.user in chat.members.all():
                chat.message_set.filter(is_read=False).exclude(author=request.user).update(is_read=True)
            else:
                chat = None
        except Chat.DoesNotExist:
            chat = None

        return render(
            request,'messenger/messages.html',
            {
                'chat': chat,
                'form': MessageForm(),
            }
        )

    def post(self, request, chat_id):
        form = MessageForm(data=request.POST)
        if form.is_valid():
            message = form.save(commit=False)
            message.chat_id = chat_id
            message.author = request.user
            message.save()
        return redirect(reverse('messenger:messages', kwargs={'chat_id': chat_id}))


def create_dialog(request, friend_id, product_id):
    duplicate = Chat.objects.filter(Q(members__id__contains=friend_id) &
                                    Q(members__id__icontains=request.user.pk))
    if duplicate.exists():
        return redirect(reverse('messenger:messages', kwargs={'chat_id': duplicate[0].pk}))
    chat = Chat.objects.create(product_id = product_id)
    chat.members.add(Account.objects.get(id=friend_id),request.user.id)
    return redirect(reverse('messenger:messages', kwargs={'chat_id': chat.pk}))


def delete_dialog(request, chat_id):
    chat = get_object_or_404(Chat, pk=chat_id)
    chat.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def get_messages(request, chat_id):
    if request.is_ajax():
        try:
            chat = Chat.objects.get(id=chat_id)

            # Проверка, что сообщение не прочитано и автор не текущий пользователь
            is_update = chat.last_message.author != request.user and not chat.last_message.is_read

            if is_update:
                if request.user in chat.members.all():
                    chat.message_set.filter(is_read=False).exclude(author=request.user).update(is_read=True)
                else:
                    chat = None
            else:
                return JsonResponse({'result': False})
        except Chat.DoesNotExist:
            chat = None

        context = {
            'chat': chat,
            'user': request.user,
        }

        result = render_to_string('messenger/message_dialog.html', context)

        return JsonResponse({'result': result})


def get_new_mes_count(request):
    user = request.user
    new_mess_count = 0
    # new_mess_count = user.chat_set.unreaded(user=user).count()
    # if new_mess_count == 0:
    #     return JsonResponse({'result': False})

    return ""


def update_chats_list(request):
    if request.is_ajax():
        context = {
            'user': request.user,
            'chats': Chat.objects.filter(members__in=[request.user.id]),
            'unread_chats': request.user.chat_set.unreaded(user=request.user)
        }

        result = render_to_string('messenger/chats_list.html', context)

        return JsonResponse({'result': result})

webkaproject/messenger/templates/messenger/chats_list.html
{% for chat in chats %}
    <div class="chat_item">
        <div class="chat_item_button">
<!--            <a href="{% url 'messenger:delete_chat' chat.pk %}" class="btn btn-danger">Удалить</a>-->
            <a href="{% url 'messenger:messages' chat.pk %}" class="btn btn-success mr-1">Открыть чат</a>
             <a href="{% url 'messenger:delete_chat' chat.pk %}" class="btn btn-danger">Удалить чат</a>
        </div>
            <div class="chat_title">
                <img class = "chat_image" src = '{{chat.product.image.url}}'>
                <a href = "{% url 'marketplace1:personal_page' pk=chat.product.author.pk %}">
                    <h5 style = 'margin: 0 0 0 0;'>{{chat.product.author.first_name}} {{chat.product.author.last_name}}</h5>
                </a>
                <h5>{{chat.product.title}}</h5>
            </div>
    </div>
{% endfor %}

webkaproject/messenger/templates/messenger/dialogs.html
{% extends 'marketplace/marketplace_main_page_base.html' %}
{% load static %}


{% block content %}
<div class="container content">
        <div class="dialogs_block">
            <h2 class="text-center">Чаты</h2>
            <h4>Ваши Чаты:</h4>
            {% if chats.count == 0 %}
                У вас еще нет созданных чатов
            {% endif %}
            <div class="chats_list">
                {% include 'messenger/chats_list.html' %}
            </div>
        </div>
    </div>
{% endblock %}

webkaproject/messenger/templates/messenger/message_dialog.html
{% load tz %}

{% if not chat %}
    Невозможно начать беседу. Не найден пользователь или вы не имеете доступа к данной беседе.
{% else %}
    {% if chat.message_set.all.count == 0 %}
        Напишите сообщение первым!
    {% endif %}
    {% for message in chat.message_set.all %}
        <div class="message_item_wrapper {% if message.author == user %}current_user{% endif %}">
            <div class="message_item{% if not message.is_read %} unread {% endif %}">
                <small>{{ message.pub_date|time:"H:i" }}</small>
                <p>{{ message.message|safe }}</p>
            </div>
        </div>
    {% endfor %}
{% endif %}

webkaproject/messenger/templates/messenger/messages.html
{% extends 'marketplace/marketplace_main_page_base.html' %}
{% load static %}

{% block content %}
    <div class="container content">
        <div class="chat_block_wrapper">
            <div class="dialog_title_wrapper flex-column">
                <a href="{% url 'messenger:dialog_list' %}" class="back_to_dialogs">Вернуться к диалогам</a>
                <div class="dialog_name">
                        {% for member in chat.members.all %}
                            {% if member.pk != user.pk %}
                                Диалог с пользователелем
                                <a href="{% url 'marketplace1:personal_page' member.pk %}">{{ member.first_name }}</a>
                            {% endif %}
                        {% endfor %}
                </div>
            </div>
            <div class="chat_block" id="chat_block">
                <div class="messages_block">
                    {% include 'messenger/message_dialog.html'%}
                </div>
                <div class="chat_form_wrapper">
                    <form method="post" class="form-inline">
                        {% csrf_token %}
                        <input name="message" class="form-control" placeholder="Ваше сообщение..." autofocus>
                        <input name="chat_pk" value="{{ chat.pk }}" type="hidden">
                        <button type="submit" class="btn btn-primary mb-2">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <script type="text/javascript">
        var block = document.getElementById("chat_block");
        block.scrollTop = 9999;
    </script>
    <script src="{% static 'js/messenges_update.js' %}"></script>
{% endblock %}