webkaproject/admin_panel/urls.py
from django.urls import path
from . import views


app_name = "admin_panel"

urlpatterns = [
    path('', views.main_admin_panel, name='admin_main'),
    path('tables/<int:pk>/', views.admin_current_table, name='admin_current_table'),

    path('accept_data', views.accept_change_data, name='accept_data'),
    path('add_modal_form', views.add_modal_form, name='add_modal_form'),

    path('accept_add_data', views.accept_add_data, name='accept_add_data'),
    path('delete_object', views.delete_object, name='delete_object'),

    path('moderate/products', views.ModerateProductList.as_view(), name='moderate_product'),
    path('moderate/products/accept/<int:pk>', views.accept_moderate_product, name='accept_moderate_product'),
    path('moderate/products/cancel/<int:pk>', views.cancel_moderate_product, name='cancel_moderate_product'),

    path('moderate/users', views.ModerateUserList.as_view(), name='moderate_user'),
    path('moderate/users/accept/<int:pk>', views.accept_moderate_user, name='accept_moderate_user'),
    path('moderate/users/cancel/<int:pk>', views.cancel_moderate_user, name='cancel_moderate_user'),

]

webkaproject/auction/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from auction.views import AuctionListView, AuctionDetailView

app_name = 'auction'

urlpatterns = [
    path('', AuctionListView.as_view(), name = 'auction_main'),
    path('lot/<int:pk>', AuctionDetailView.as_view(), name = 'auction_detail')
]

webkaproject/authorization/urls.py
from django.urls import path
from . import views
from account.views import registration_view
app_name = 'authorization'

urlpatterns = [
    path('reg/', registration_view, name='reg_page'),
    path('', views.AuthUserView.as_view(), name='auth_page'),
    path('logout', views.LogoutView.as_view(), name='logout'),

]

webkaproject/marketplace1/urls.py
from django.urls import path
from . import views


app_name = "marketplace1"

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('product/<int:pk>/', views.product_detail, name='product_detail'),
    path('delete/<int:product_id>/', views.delete_product, name='delete_product'),
    path('product/new/', views.NewProductView.as_view(), name='product_new'),
    path('product/<int:pk>/edit', views.product_edit, name='product_edit'),
    path('personal/<int:pk>', views.Personal.as_view(), name='personal_page'),
    path('refill', views.BalanceRefill.as_view(), name='refill_page'),
    path('search', views.SearchResultsView.as_view(), name='search_results'),
    path('favorite', views.FavoriteProductsList.as_view(), name='favorite_products'),
    path('product/<int:pk>/favorite_add', views.add_favorite_product, name='add_favorite_product'),
    path('product/<int:pk>/favorite_delete', views.delete_favorite_product, name='delete_favorite_product'),
    path('product/<int:pk>/favorite_list_delete', views.delete_from_favorit_list, name='delete_from_favorit_list'),
    path('personal/<int:pk>/edit', views.personal_edit, name='personal_edit'),

]

webkaproject/messenger/urls.py
from django.urls import path
from . import views


app_name = "messenger"

urlpatterns = [
    path('', views.Dialog_list.as_view(), name='dialog_list'),
    path('<chat_id>/', views.MessagesView.as_view(), name='messages'),
    path('create/<friend_id>/<product_id>', views.create_dialog, name='create_dialog'),
    path('delete/<chat_id>/', views.delete_dialog, name='delete_chat'),

    path('get_messages/<chat_id>/', views.get_messages, name='get_messages'),
    path('get/new_mes_count/', views.get_new_mes_count, name='get_new_mes_count'),
    path('get/update_dialogs/', views.update_chats_list, name='update_dialogs'),
]

webkaproject/webkaproject/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns = [
        path('admin/', admin.site.urls),
        path('', include('marketplace1.urls')),
        path('auth/', include('authorization.urls')),
        path('auc/', include('auction.urls')),
        path('dialogs/', include('messenger.urls')),
        path('admin1/', include('admin_panel.urls')),

    ]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#
# else:
#     urlpatterns = [
#         path('admin/', admin.site.urls),
#         path('', include('marketplace1.urls')),
#         path('auth/', include('authorization.urls')),
#         path('auc/', include('auction.urls')),
#         path('dialogs/', include('messenger.urls')),
#     ]

webkaproject/marketplace1/models.py
from django.conf import settings


from django.db import models
from django.utils import timezone
from django.dispatch import receiver
import os
from webkaproject.settings import STATIC_URL,STATIC_ROOT
class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

class Product(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    category = models.ForeignKey(Category, related_name = "products", on_delete = models.CASCADE)

    title = models.CharField(max_length=200, verbose_name="Название")
    description = models.TextField(verbose_name="Описание")
    published_date = models.DateTimeField(blank=True, null=True)
    cost = models.fields.IntegerField(blank=False, null=True, verbose_name="Цена")
    image = models.ImageField(blank=True, null=True, verbose_name="Изображение", upload_to='product_images/', default="no_image.png")
    is_active = models.BooleanField(default = False)
    is_moderated = models.BooleanField(default = False)



    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

    # def delete(self, *args, **kwargs):
    #     self.image.delete()
    #     super(Product, self).delete(*args, **kwargs)

    class Meta:
        verbose_name = 'Продукт(товар)'
        verbose_name_plural = 'Продукты(товары)'

class FavoriteProduct(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    def __str__(self):
        return self.product +'-'+self.user
    class Meta:
        verbose_name = 'Избранный товар'
        verbose_name_plural = 'Избранные товары'



@receiver(models.signals.post_delete, sender=Product)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    """
    Удаление изображений из файловой системы
    """
    if instance.image:
        if os.path.isfile(instance.image.path):
            os.remove(instance.image.path)


@receiver(models.signals.pre_save, sender=Product)
def auto_delete_file_on_change(sender, instance, **kwargs):
    """
    Удаление старых изображений из файловой системы при обновлении
    """
    if not instance.pk:
        return False

    try:
        old_file = Product.objects.get(pk=instance.pk).image
        if not old_file:
            return False
    except Product.DoesNotExist:
        return False

    new_file = instance.image
    if not old_file == new_file:
        if os.path.isfile(old_file.path):
            os.remove(old_file.path)

webkaproject/marketplace1/forms.py
from django import forms

from .models import Product
from account.models import Account


class PersonalEditForm(forms.ModelForm):

    class Meta:
        model = Account
        fields = ("email", "first_name", "last_name", "username", "country", "cellphone", "avatar",)

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)

class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = ('category', 'title', 'description', 'cost', 'image', )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['category'].widget.attrs['class'] = 'input_field'
        self.fields['category'].empty_label = 'Выберите категорию товара'
        self.fields['category'].widget.attrs['placeholder'] = 'Категория'
        self.fields['category'].label = ''

        self.fields['title'].widget.attrs['class'] = 'input_field'
        self.fields['title'].widget.attrs['placeholder'] = 'Название'
        self.fields['title'].label = ''

        self.fields['description'].widget.attrs['class'] = 'opisanie'
        self.fields['description'].widget.attrs['placeholder'] = 'Описание'
        self.fields['description'].label = ''

        self.fields['cost'].widget.attrs['class'] = 'input_field'
        self.fields['cost'].widget.attrs['placeholder'] = 'Цена'
        self.fields['cost'].label = ''

        # self.fields['username'].label = ''

        # self.fields['password'].widget.attrs['class'] = 'password_input'
        # self.fields['password'].label = ''

webkaproject/marketplace1/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic.base import View
from .models import Product, Category, FavoriteProduct
from account.models import Account
from .forms import ProductForm, PersonalEditForm
from django.shortcuts import redirect
from django.utils import timezone
from django.views.generic import CreateView, View, TemplateView, ListView, DeleteView
from django.urls import reverse_lazy
from django.db.models import Q
from decimal import *
from django.http import HttpResponse,HttpResponseRedirect,HttpResponseNotFound
from django.templatetags.static import static
from django.http import JsonResponse
from django.template.loader import render_to_string
from account.forms import RegistrationForm
from django.contrib.auth import authenticate, login
from django.core.files.storage import FileSystemStorage

categories = Category.objects.all()

def product_list(request):
    products = Product.objects.filter(published_date__lte=timezone.now()).order_by("published_date")
    return render(request, 'marketplace/content.html', {'products': products , 'categories':categories})


def product_detail(request, pk):
    product = get_object_or_404(Product, pk=pk)
    is_fav = False
    fav = False
    try:
        if request.user.is_authenticated :
            fav = FavoriteProduct.objects.get(user=request.user, product=product)
    except FavoriteProduct.DoesNotExist:
        fav = False
    if fav:
        is_fav = True
    return render(request, 'marketplace/product_detail.html', {'product': product,'categories': categories, 'is_fav':is_fav})


class NewProductView(CreateView):
    model = Product
    form_class = ProductForm
    template_name = 'marketplace/product_new.html'
    success_url = reverse_lazy('marketplace1:product_list')


    # def post(self, request, *args, **kwargs):
    #     form =  ProductForm(request.POST)
    #
    #     if form.is_valid():
    #         image = form.cleaned_data['image']
    #         # <process form cleaned data>
    #         return HttpResponseRedirect('/success/')
    # <view logic>
    def form_valid(self, form):
        new_product = form.save(commit=False)
        new_product.author = self.request.user
        new_product.published_date = timezone.now()
        new_product.save()
        return super().form_valid(form)

class Personal (View):
    def get(self, request, *args, **kwargs):
        account_pk = self.kwargs['pk']
        user = self.request.user
        if user.is_authenticated:
            cur_user = user
        cur_user = Account.objects.get(pk=account_pk)
        # if cur_user:
        users_products = Product.objects.filter(author=cur_user)
        return render(self.request, 'personal/personal_main.html', {'cur_user': cur_user, 'users_products': users_products, 'categories': categories})

class BalanceRefill (TemplateView):
    template_name = 'marketplace/refill.html'

    def post(self, request, *args, **kwargs):
        cur_user = Account.objects.get(user = request.user)
        money = Decimal(request.POST['count_money'])
        cur_user.balance += money

        cur_user.save()
        return render(request, 'marketplace/refill.html')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        return context

def product_edit(request, pk):
    product = get_object_or_404(Product, pk=pk)
    if request.method == "POST":
        form = ProductForm(request.POST, instance=product)
        if form.is_valid():
            product = form.save(commit=False)
            product.author = request.user
            product.published_date = timezone.now()
            product.save()
            return redirect('marketplace1:product_detail', pk=product.pk)

    else:
        form = ProductForm(instance=product)
    return render(request, 'marketplace/product_edit.html', {'form': form, 'product_pk':product.pk,'categories': categories})

class SearchResultsView(ListView):
    model = Product
    template_name = 'marketplace/product_search_results.html'

    def get_queryset(self):
        query = self.request.GET.get('q')
        #print(query+"fdfdfdfefef")
        category = self.request.GET.get('category')
        if category == '-1' :
            product_list = Product.objects.filter(
            Q(title__icontains=query))
        elif query == None:
            product_list = Product.objects.filter(
                Q(category_id=category))
        else:
            product_list = Product.objects.filter(
                Q(title__icontains=query) & Q(category_id=category))

        return product_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = categories
        return context

def delete_product(request, product_id):
    try:
        product = Product.objects.get(id=product_id)
        product.delete()
        return HttpResponseRedirect(reverse_lazy("marketplace1:product_list"))
    except Product.DoesNotExist:
        return HttpResponseNotFound("<h2>Person not found</h2>")

class FavoriteProductsList(ListView):
    model = FavoriteProduct
    template_name = 'marketplace/favorite_products_list.html'
    def get_context_data(self, *, object_list=None, **kwargs):
        data = {'favorites': FavoriteProduct.objects.filter(user=self.request.user)}
        temp = FavoriteProduct.objects.filter(user=self.request.user)
        return data

def add_favorite_product(request,pk):

    if request.is_ajax():
        product = Product.objects.get(pk=pk)
        favorite = FavoriteProduct(user=request.user, product=product)
        favorite.save()
        context = {}
        context['is_fav'] = True
        context['product'] = product
        result = render_to_string('includes/favorite_block.html', context)
        return JsonResponse({'result': result})

def delete_favorite_product(request,pk):

    if request.is_ajax():
        try:
            product = Product.objects.get(pk=pk)
            favorite = FavoriteProduct.objects.get(user=request.user, product=product)
            favorite.delete()
            context = {}
            context['is_fav'] = False
            context['product'] = product
            result = render_to_string('includes/favorite_block.html', context)
            return JsonResponse({'result': result})
        except Product.DoesNotExist:
            return HttpResponseNotFound("<h2>Favorite not found</h2>")

def delete_from_favorit_list(request,pk):
    if request.is_ajax():
        try:
            print("sdadsad")
            product = Product.objects.get(pk=pk)
            favorite = FavoriteProduct.objects.get(user=request.user, product=product)
            favorite.delete()
            return JsonResponse({'result': 'success'})
        except Product.DoesNotExist:
            return HttpResponseNotFound("<h2>Favorite not found</h2>")

def personal_edit(request,pk):
    cur_user = Account.objects.get(pk=pk)
    if request.method == "POST":
        form = PersonalEditForm(request.POST, instance=cur_user)


        print(request.FILES)
        if form.is_valid():

            cur_user = form.save(commit=False)
            if request.FILES:
                fs = FileSystemStorage()
                avatar_file = fs.save(('user_images/' + request.FILES['avatar'].name), request.FILES['avatar'])
                cur_user.avatar = 'user_images/' + str(request.FILES['avatar'])
                print(cur_user.avatar)
            cur_user.save()
            login(request,cur_user)
            return redirect('marketplace1:personal_page', pk=cur_user.pk)


    else:
        form = PersonalEditForm(instance=cur_user)
    return render(request, 'personal/personal_edit.html',
                  {'form': form,})

webkaproject/marketplace1/templates/marketplace/favorite_products_list.html
{% extends 'marketplace/marketplace_main_page_base.html' %}
{% load static %}

{% block content %}
<div class="container content">
        <div class="dialogs_block">
            <h2 class="text-center">Избранные товары</h2>
            <h4>Ваши избранные:</h4>
            {% if favorites %}
            <div class="chats_list">
                {% include 'includes/favorite_item.html' %}
            </div>
            {% else %}
            <p>Избранных товаров нет =(</p>
            {% endif %}
        </div>
    </div>




{% endblock %}

webkaproject/marketplace1/templates/marketplace/marketplace_main_page_base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru" xmlns="http://www.w3.org/1999/html">

<head>
    <meta charset="UTF-8">
    {% block title %}<title>Geek Soft - Главная</title> {% endblock %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/main_page.css' %}">
    {% block css %}
    {% endblock %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://unpkg.com/@popperjs/core@2.11.0/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>


</head>

<body>
<div class="container">
    <header>
        <div class="row">
            <div class="col-6 location">
                <p>Местоположение: <a href="#">Иркутск</a></p>
            </div>
            <div class="col-6">
                <ul class="nav-actions">
                    {% if user.is_admin %}
                    <li><a href={% url 'admin_panel:admin_main' %}>Администрирование</a></li>{% endif %}

                    <li><a href=
                            {% if user.is_authenticated %}
                                {% url 'messenger:dialog_list' %}
                            {% else %}
                                {% url 'authorization:auth_page' %}
                            {% endif %}>Сообщения</a></li>

                    <li><a href=
                            {% if user.is_authenticated %}
                                {% url 'marketplace1:favorite_products' %}
                            {% else %}
                                {% url 'authorization:auth_page' %}
                            {% endif %}>Избранное</a></li>
                </ul>
            </div>
        </div>
        <div class="row">
            <div class="col-1">
                <div class="logo">
                    <a href="{%url 'marketplace1:product_list' %}">LOGO</a>
                </div>
            </div>
            <form class="input-group col-md-8" , action="{% url 'marketplace1:search_results' %}" , method="GET">
                <div class="input-group-btn">
                    <select name='category' , class="categories_btn">
                        <option value="-1" active>Категория</option>
                        -->
                        {% for category in categories %}
                        <option value={{ category.id }}>{{category}}</option>
                        {% endfor %}
                    </select>
                </div>
                <input name='q' type="text" name="search[input]" placeholder="Поиск объявления..."
                       class="form-control"/>
                <div class="input-group-btn">
                    <button type="submit" class="btn">Поиск <i class="glyphicon glyphicon-search"></i></button>
                </div>
            </form>
            <!--                <div class="categories_btn">-->
            <!--
            <!--                </div>-->
            <!--            <div class="col-6">-->
            <!--                <form action="{% url 'marketplace1:search_results' %}", method = "GET">-->
            <!--                    <input name = "q" type="text" placeholder="Поиск по объялениям">-->
            <!--                    <button type="submit" name="button">Найти</button>-->
            <!--                </form>-->
            <!--                <p>Баланс:{{ user.userdetails.balance }}</p>-->
            <!--            </div>-->
            <div class="col-2">
                <div class="make_product">
                    <span>
                        <a href=
                                   {% if user.is_authenticated %}
                           {% url 'marketplace1:product_new' %}

                                    {% else %}
                                        {% url 'authorization:auth_page' %}
                                   {% endif %}>Разместить объяление</a>
                    </span>
                </div>
            </div>
            <div class="col-1">
                {% if user.is_authenticated %}
                <a href="{% url 'marketplace1:personal_page' pk=user.pk %}">
                    <div class="presonal_room">Л.К.</div>
                    {{ user.first_name }}
                </a>
                <a href="{% url 'authorization:logout' %}">
                    <div class="logout">Выйти</div>
                </a>
                {% else %}
                <a href="{% url 'authorization:auth_page' %}" class="go_auth">
                    <div class='go_auth_btn'>Войти</div>
                </a>
                {% endif %}
            </div>
        </div>
    </header>
    <main>
        {% block carousel %}
        {% endblock %}

        {% block content %}
        {% endblock %}

    </main>
</div>

<script src="{% static 'js/admin_actions.js' %}"></script>
<script src="{% static 'js/product_actions.js' %}"></script>
</body>

</html>

webkaproject/marketplace1/templates/marketplace/product_detail.html
{% extends 'marketplace/marketplace_main_page_base.html' %}
{% load static %}
{% block content %}
<div class="detail_foundation">
    <div class="detail_product">
        <div class="detail_category">
            <h7>Категория:/</h7>
            <a href="{% url 'marketplace1:search_results'%}?category={{product.category.pk}}">
                <h7>{{product.category}}</h7>
            </a>
        </div>
        <div class="detail_title">
            <h1>{{ product.title }}</h1>
        </div>
        <div class="detail_img">
            {% if product.image %}
            <img src={{ product.image.url }}>
            {% else %}
            <img src="{% static 'img/no_image.png' %}">
            {% endif %}
        </div>
        <div class="detail_description">
            <hr style="margin-bottom:0px;">
            <h3>Описание:</h3>
            <p>{{ product.description|linebreaksbr }}</p>
        </div>
        <hr style="margin-bottom:0px;">
        {% if product.published_date %}
        <div class="date">

            <p>Размещено: {{ product.published_date }}</p>
        </div>
        {% endif %}

        {% if user == product.author %}
        <a class="btn btn-warning" href="{% url 'marketplace1:product_edit' pk=product.pk %}"><span
                class="glyphicon glyphicon-pencil">Редактировать</span></a>
        {% endif %}
    </div>

    <div class="contact_block">
        <h1>{{ product.cost }}₽</h1>
        {% if not user.is_authenticated %}
        <h4 style='color:#ff7a7a;'>Что бы связаться с продавцом, необходма <a style='color:#ff7a7a;'
                                                                              href="{% url 'authorization:auth_page' %}">
            <h4> авторизация </h4></a></h4>
        {% elif user.is_authenticated %}
        {% if product.author != user %}
        <h3>Связаться с продавцом:</h3>
        <a href="{% url 'marketplace1:personal_page' pk=product.author.pk %}"><h4>{{product.author.first_name}}
            {{product.author.last_name}}</h4></a>
        <h4>Номер телефона:{{product.author.cellphone}}</h4>
        <form action="{% url 'messenger:create_dialog' friend_id=product.author.pk product_id=product.id%}">
            <button class="btn btn-primary" type="submit">Написать</button>
        </form>
        {% else %}
        <form action="{% url 'marketplace1:delete_product' product_id=product.pk %}">
            <button class="btn btn-danger" type="submit">Убрать с продажи</button>
        </form>
        {% endif %}
        <div class="favorite_block">
            {% include "includes/favorite_block.html" %}
        </div>

        {% endif %}
    </div>
</div>

{% endblock %}

webkaproject/marketplace1/templates/marketplace/product_edit.html
{% extends 'marketplace/marketplace_main_page_base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/product_new.css' %}">
{% endblock %}

{% block content %}
<div class = "product">

    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button class = "btn btn-success" type="submit">Разместить</button>
        <a class = "btn btn-danger" href="{%url 'marketplace1:product_detail' pk=product_pk%}">Отмена</a>
    </form>
</div>
{% endblock %}

webkaproject/marketplace1/templates/marketplace/product_new.html
{% extends 'authorization/auth_base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/product_new.css' %}">
{% endblock %}

{% block title %}
<title>Разместить объявление</title>
{% endblock %}

{% block content %}

<div class = "product">


    <h1>Разместить объявление</h1>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}

        <button class = "btn btn-success" type="submit">Разместить</button>

        <a class="btn btn-danger" href="{% url 'marketplace1:product_list' %}" role="button">Отмена</a>

    </form>

</div>
{% endblock %}

webkaproject/marketplace1/templates/marketplace/product_search_results.html
{% extends 'marketplace/marketplace_main_page_base.html' %}
{% load static %}

{% block content %}
<div class="row">
    <div>
        <div class="content">
            <h2 style="    margin-top: 55px;">Все объявления</h2>

                <div class="product_blocks-block">
                {% if not product_list %}
                    <h4>По вашему запросу ничего не найдено</h4>
                {% else %}
                    {% for product in product_list %}
                        <a href="{% url 'marketplace1:product_detail' pk=product.pk %}">
                            <div class="product_card">

                                <div class="product_card-logo">
                                    {% if product.image %}<img src ="{{ product.image.url }}">
                                    {% else %} <img src ="{% static 'img/no_image.png' %}">
                                    {% endif %}
                                </div>
                                <div class ="product_title_div">
                                    <span class="product_card-title">{{product.title}}</span>
                                </div>
                                <div>
                                    <span class="product_card-price">{{product.cost}}₽</span>
                                </div>
                        </a>
                            </div>
                        </a>
                    {% endfor %}
                {% endif %}
                </div>

        </div>
    </div>
</div>
{% endblock %}

webkaproject/marketplace1/templates/marketplace/refill.html
{% extends 'marketplace/marketplace_main_page_base.html' %}
{% load static %}

{% block content %}
<div>
    <h2>Логин: {{ user.username }}</h2>
    <h2>Баланс: {{ user.userdetails.balance }}</h2>
    <br>
    <h3>Пополнение</h3>

    <form action="{% url 'marketplace1:refill_page' %}" method="post">
        {% csrf_token %}
        <input type="number" name="count_money" min="1" max="1000" >₽
        <br>
        <br>
        <input type="submit" value="Пополнить">
    </form>

</div>
{% endblock %}