webkaproject/admin_panel/urls.py
from django.urls import path
from . import views


app_name = "admin_panel"

urlpatterns = [
    path('', views.main_admin_panel, name='admin_main'),
    path('tables/<int:pk>/', views.admin_current_table, name='admin_current_table'),

    path('accept_data', views.accept_change_data, name='accept_data'),
    path('add_modal_form', views.add_modal_form, name='add_modal_form'),

    path('accept_add_data', views.accept_add_data, name='accept_add_data'),
    path('delete_object', views.delete_object, name='delete_object'),

    path('moderate/products', views.ModerateProductList.as_view(), name='moderate_product'),
    path('moderate/products/accept/<int:pk>', views.accept_moderate_product, name='accept_moderate_product'),
    path('moderate/products/cancel/<int:pk>', views.cancel_moderate_product, name='cancel_moderate_product'),

    path('moderate/users', views.ModerateUserList.as_view(), name='moderate_user'),
    path('moderate/users/accept/<int:pk>', views.accept_moderate_user, name='accept_moderate_user'),
    path('moderate/users/cancel/<int:pk>', views.cancel_moderate_user, name='cancel_moderate_user'),

]

webkaproject/auction/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from auction.views import AuctionListView, AuctionDetailView

app_name = 'auction'

urlpatterns = [
    path('', AuctionListView.as_view(), name = 'auction_main'),
    path('lot/<int:pk>', AuctionDetailView.as_view(), name = 'auction_detail')
]

webkaproject/webkaproject/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns = [
        path('admin/', admin.site.urls),
        path('', include('marketplace1.urls')),
        path('auth/', include('authorization.urls')),
        path('auc/', include('auction.urls')),
        path('dialogs/', include('messenger.urls')),
        path('admin1/', include('admin_panel.urls')),

    ]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#
# else:
#     urlpatterns = [
#         path('admin/', admin.site.urls),
#         path('', include('marketplace1.urls')),
#         path('auth/', include('authorization.urls')),
#         path('auc/', include('auction.urls')),
#         path('dialogs/', include('messenger.urls')),
#     ]

webkaproject/admin_panel/models.py
from django.db import models

# Create your models here.

webkaproject/admin_panel/forms.py
from django import forms
from bootstrap_modal_forms.generic import BSModalCreateView
import models

webkaproject/admin_panel/views.py
from django.shortcuts import render
from django.apps import apps
from django.shortcuts import get_object_or_404
from django.forms import modelform_factory, inlineformset_factory
from django.forms.models import fields_for_model
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView
from django.shortcuts import redirect
from account.models import Account
from marketplace1.models import Product
from django.contrib import messages



class Counter:
    count = 0

    def increment(self):
        self.count += 1
        return ''

    def decrement(self):
        self.count -= 1
        return ''

    def double(self):
        self.count *= 2
        return ''


from django.forms import ModelForm
from django.forms.models import model_to_dict
from django.template.loader import render_to_string
from django.http import JsonResponse


def get_model(num):
    mods = apps.get_models()  # все модели
    model_names = []
    models = []
    for mod in mods:
        if mod._meta.verbose_name[0].isupper():
            model_names.append(mod._meta.verbose_name)
            models.append(mod)
    return models[num]


def get_values_of_objects(objects, object_fields):
    values = []
    for obj in objects:
        temp = []
        for field in object_fields:
            temp.append(getattr(obj, field.name))
        values.append(temp)
    return values


def main_admin_panel(request):
    mods = apps.get_models()  # все модели
    model_names = []
    for mod in mods:
        if mod._meta.verbose_name[0].isupper():
            model_names.append(mod._meta.verbose_name)

    counter = Counter()

    return render(request, 'admin_panel/main_admin_list_page.html', {'table_names': model_names, 'counter': counter})


@csrf_exempt
def admin_current_table(request, pk):
    context = {}
    selected_model = get_model(pk)  # выбранная пользователем модель(тип данных)

    selected_model_fields = selected_model._meta.fields  # поля принадлежащие модели

    selected_model_objects = selected_model.objects.order_by(
        'id')  # все объекты выбранного типа данных отсортированные по id

    values_of_fields = get_values_of_objects(selected_model_objects, selected_model_fields)  # значения объекта

    field_names = []  # имена полей(столбцов таблицы)

    if request.method == "POST":
        obj_id = request.POST.get('object_id')

        for field in selected_model_fields:  # получаем список имён полей для генерации формы
            if field.editable:
                field_names.append(field.name)

        temp_form = modelform_factory(selected_model,
                                      fields=field_names)  # Форма для выбранного объекта, может используется для создания новой формы, поэтому temp
        obj = get_object_or_404(selected_model, pk=obj_id)  # получаем объект выбранной модели
        form = temp_form(instance=obj)
        modal_context = {
            'form': form,
            'user': request.user,
            'obj': obj,
            'selected_model_name': selected_model._meta.verbose_name,
            'selected_model_objects': selected_model_objects,
            'fields': selected_model_fields,
            'values_of_fields': values_of_fields,
            'tabnum': int(pk),
        }
        result = render_to_string('includes/modal_change_object.html', modal_context)
        return JsonResponse({'result': result})

    context['selected_model_name'] = selected_model._meta.verbose_name
    context['selected_model_objects'] = selected_model_objects
    context['fields'] = selected_model_fields
    context['values_of_fields'] = values_of_fields
    context['tabnum'] = int(pk)

    return render(request, 'admin_panel/admin_table.html', context, )


@csrf_exempt
def accept_change_data(request):
    if request.method == 'POST':
        context = {}
        selected_model = get_model(int(request.POST.get('tab_id')))  # выбранная пользователем модель(тип данных)
        obj = get_object_or_404(selected_model,
                                pk=int(request.POST.get('object_id')))  # получаем объект выбранной модели
        selected_model_objects = selected_model.objects.order_by(
            'id')  # все объекты выбранного типа данных отсортированные по id

        selected_model_fields = selected_model._meta.fields  # поля принадлежащие модели
        field_names = []  # имена полей(столбцов таблицы)
        for field in selected_model_fields:  # получаем список имён полей для генерации формы
            if field.editable:
                field_names.append(field.name)

        temp_form = modelform_factory(selected_model,
                                      fields=field_names)

        form = temp_form(request.POST, instance=obj)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.save()
        values_of_fields = get_values_of_objects(selected_model_objects, selected_model_fields)  # значения объекта
        context['selected_model_name'] = selected_model._meta.verbose_name
        context['selected_model_objects'] = selected_model_objects
        context['fields'] = selected_model_fields
        context['values_of_fields'] = values_of_fields
        context['tabnum'] = int(request.POST.get('tab_id'))
        context['script_path'] = "/static/js/admin_actions.js"
        result = render_to_string('includes/table_objects.html', context)
        return JsonResponse({'result': result})

        # return render(request, 'admin_panel/admin_table.html', context)


@csrf_exempt
def add_modal_form(request):
    if request.method == "POST":
        context = {}
        selected_model = get_model(int(request.POST.get('tab_id')))  # выбранная пользователем модель(тип данных)
        selected_model_fields = selected_model._meta.fields  # поля принадлежащие модели
        field_names = []  # имена полей(столбцов таблицы)
        for field in selected_model_fields:  # получаем список имён полей для генерации формы
            if field.editable:
                field_names.append(field.name)
        add_form = modelform_factory(selected_model,
                                     fields=field_names)  # Форма для выбранного объекта, может используется для создания новой формы, поэтому temp

        context["add_form"] = add_form
        context['selected_model_name'] = selected_model._meta.verbose_name
        context['tabnum'] = int(request.POST.get('tab_id'))
        result = render_to_string('includes/modal_add_object.html', context)
        return JsonResponse({'result': result})


@csrf_exempt
def accept_add_data(request):
    if request.method == "POST":
        context = {}
        selected_model = get_model(int(request.POST.get('tab_id')))  # выбранная пользователем модель(тип данных)

        selected_model_objects = selected_model.objects.order_by(
            'id')  # все объекты выбранного типа данных отсортированные по id
        selected_model_fields = selected_model._meta.fields  # поля принадлежащие модели
        field_names = []  # имена полей(столбцов таблицы)
        for field in selected_model_fields:  # получаем список имён полей для генерации формы
            if field.editable:
                field_names.append(field.name)

        temp_form = modelform_factory(selected_model, fields=field_names)
        form = temp_form(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            print('форма валидная')
            if selected_model == Account:
                obj.set_password(form.cleaned_data['password'])

            obj.save()
        else:
            context_modal_add = {}
            context_modal_add['add_form'] = form
            context_modal_add['tabnum'] = int(request.POST.get('tab_id'))
            print(form.errors)
            result = render_to_string('includes/modal_add_object.html', context_modal_add)
            return JsonResponse({'errors': form.errors, 'result': result})

        values_of_fields = get_values_of_objects(selected_model_objects, selected_model_fields)  # значения объекта

        context['selected_model_name'] = selected_model._meta.verbose_name
        context['selected_model_objects'] = selected_model_objects
        context['fields'] = selected_model_fields
        context['values_of_fields'] = values_of_fields
        context['tabnum'] = int(request.POST.get('tab_id'))
        context['script_path'] = "/static/js/admin_actions.js"
        result = render_to_string('includes/table_objects.html', context)
        return JsonResponse({'result': result})


@csrf_exempt
def delete_object(request):
    if request.method == "POST":
        context = {}
        selected_model = get_model(int(request.POST.get('tab_id')))  # выбранная пользователем модель(тип данных)
        selected_model_objects = selected_model.objects.order_by(
            'id')  # все объекты выбранного типа данных отсортированные по id
        selected_model_fields = selected_model._meta.fields  # поля принадлежащие модели
        field_names = []  # имена полей(столбцов таблицы)
        for field in selected_model_fields:  # получаем список имён полей для генерации формы
            if field.editable:
                field_names.append(field.name)

        obj = get_object_or_404(selected_model,
                                pk=int(request.POST.get('object_id')))  # получаем объект выбранной модели
        obj.delete()
        values_of_fields = get_values_of_objects(selected_model_objects, selected_model_fields)  # значения объекта

        context['selected_model_name'] = selected_model._meta.verbose_name
        context['selected_model_objects'] = selected_model_objects
        context['fields'] = selected_model_fields
        context['values_of_fields'] = values_of_fields
        context['tabnum'] = int(request.POST.get('tab_id'))
        context['script_path'] = "/static/js/admin_actions.js"
        result = render_to_string('includes/table_objects.html', context)

webkaproject/admin_panel/templates/admin_panel/admin_table.html
{% extends 'marketplace/marketplace_main_page_base.html' %}
{% load static %}


{% block css %}
<link rel="stylesheet" href="{% static 'css/admin_panel.css' %}">
{% endblock %}

{% block content %}
<div class="container-content">
    <a class="list-group-item list-group-item-action bg-info text-dark"
       href="{% url 'admin_panel:admin_main' %}">Назад</a>
    <h2 class="zagolovok">Администрирование таблицы БД</h2>
</div>

<h4 class="zagolovok">Таблица: {{ selected_model_name }}</h4>

<form>
    <input type="hidden" name="tab_id" value="{{ tabnum }}">
    <button id="addButton" type="button" data-url="{% url 'admin_panel:add_modal_form' %}"
            name="addButton" class="btn btn-primary">Добавить {{ selected_model_name }}
    </button>
</form>
<div id="table_block" class="table_block">
    {% include 'includes/table_objects.html'%}
</div>
<div id="modal_window">
    {% include 'includes/modal_change_object.html'%}
</div>
<div id="modal_add_window">
    {% include 'includes/modal_add_object.html'%}
</div>


{% endblock %}

webkaproject/admin_panel/templates/admin_panel/edit_table.html
{% extends 'marketplace/marketplace_main_page_base.html' %}
{% load static %}
{% block title %}<title>Редактирование таблицы </title>{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/admin_panel.css' %}">
{% endblock %}

{% block content %}

<form method="POST" class="zagolovok">
    <h4 class="zagolovok">{{ selected_model_name }} - {{ obj }}</h4>

    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-success" type="submit">Разместить</button>
    <a class="btn btn-danger" href="{%url 'admin_panel:admin_current_table' pk=tabnum%}">Отмена</a>
</form>

{% endblock %}

webkaproject/admin_panel/templates/admin_panel/main_admin_list_page.html
{% extends 'marketplace/marketplace_main_page_base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/admin_panel.css' %}">
{% endblock %}

{% block content %}

<h2 class="zagolovok">Администрирование</h2>

<div class="card-deck mb-4 text-center">
    <div class="card">
        <div class="card-header">
            Таблицы БД
        </div>
        <ul class="list-group list-group-flush">
            {% for table_name in table_names %}
            <a class="list-group-item list-group-item-action" href="{% url 'admin_panel:admin_current_table' pk=counter.count %}">{{ table_name }}</a>
            {{ counter.increment }}
            {% endfor %}
        </ul>
    </div>
    <div class="card" style="height: 139px">
        <div class="card-header">
            Модерирование
        </div>
        <ul class="list-group list-group-flush">
                <a class="list-group-item list-group-item-action" href="{% url 'admin_panel:moderate_product' %}">Товары</a>
                <a class="list-group-item list-group-item-action" href="{% url 'admin_panel:moderate_user' %}">Пользователи</a>
        </ul>
    </div>
</div>
{% endblock %}

webkaproject/admin_panel/templates/admin_panel/product_moderate.html
{% extends 'marketplace/marketplace_main_page_base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/admin_panel.css' %}">
{% endblock %}

{% block content %}
<a class="list-group-item list-group-item-action bg-info text-dark"
       href="{% url 'admin_panel:admin_main' %}">Назад</a>
<div class="container content">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h2 class="text-center">Модерация товаров</h2>

            {% for product in products %}
            <div id="product_block-{{product.id}}"
                 class="moderate_product_block d-flex align-items-center news-moderate_wrap">
                {% include 'includes/inc_product_item.html' %}
                <div class="product-moderate_btns">
                    <button onclick="accept_product({{ product.pk }})"
                            class="accept_product_button btn btn-outline-success"
                            data-url="{% url 'admin_panel:accept_moderate_product' pk=product.id%}">
                        OK
                        <i class="fa fa-check" aria-hidden="true"></i>
                    </button>

                    <button onclick="cancel_product({{ product.pk }})"
                            class="cancel_product_button btn btn-outline-danger"
                            data-url="{% url 'admin_panel:cancel_moderate_product' pk=product.id%}">
                        X
                        <i class="fa fa-ban" aria-hidden="true"></i>
                    </button>
                </div>
            </div>
            {% endfor %}

            {% if not products %}
            <p class="text-center">Нет товаров для модерации</p>
            {% endif %}

            <!--                <a href="{% url 'admin_panel:moderate_product' %}" class="btn btn-success">Завершить модерирование</a>-->

        </div>
    </div>
</div>
{% endblock %}

webkaproject/admin_panel/templates/admin_panel/user_moderate.html
{% extends 'marketplace/marketplace_main_page_base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/admin_panel.css' %}">
{% endblock %}

{% block content %}
<a class="list-group-item list-group-item-action bg-info text-dark"
       href="{% url 'admin_panel:admin_main' %}">Назад</a>
<div class="container content">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h2 class="text-center">Модерация пользователей</h2>

            {% for acc in accs %}
            <div id="user_block-{{acc.id}}"
                 class="moderate_user_block d-flex align-items-center news-moderate_wrap">
                {% include 'includes/inc_user_item.html' %}
                <div class="acc-moderate_btns">
                    <button onclick="accept_user({{ acc.pk }})"
                            class="accept_user_button btn btn-outline-success"
                            data-url="{% url 'admin_panel:accept_moderate_user' pk=acc.id%}">
                        OK
                        <i class="fa fa-check" aria-hidden="true"></i>
                    </button>

                    <button onclick="cancel_user({{ acc.pk }})"
                            class="cancel_user_button btn btn-outline-danger"
                            data-url="{% url 'admin_panel:cancel_moderate_user' pk=acc.id%}">
                        X
                        <i class="fa fa-ban" aria-hidden="true"></i>
                    </button>
                </div>
            </div>
            {% endfor %}

            {% if not accs %}
            <p class="text-center">Нет пользователей для модерации</p>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}